In [165]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [166]:
df_dep = pd.read_csv('departamentos-pro.csv', dtype="string")
df_casa = pd.read_csv('casas-pro.csv', dtype="string")

def limpiar(precios):
    lista=precios
    lista=lista.str.replace("MN ", "", regex=True).str.replace("$","",regex=False).str.replace(",","",regex=False)    
    lista=pd.to_numeric(lista,errors="coerce")    
    return lista

def limpiar_m(metros):
    lista=metros
    lista=lista.str.replace(" m²","",regex=True)
    lista=pd.to_numeric(lista,errors="coerce")
    return lista

In [167]:
#MODELO PARA DEPARTAMENTOS

df_dep['nprecio']=limpiar(df_dep['precio'])
df_dep['nprecio']=df_dep['nprecio'].replace(0,np.NaN)
df_dep['nmetros']=limpiar_m(df_dep['mets'])
df_dep['nmetros']=df_dep['nmetros'].replace(0,np.NaN)
model_departamentos=linear_model.LinearRegression()

#DATA FRAME DE ENTRENAMIENTO (70% de los datos) = departamentos
departamentos1=pd.DataFrame(df_dep.loc[df_dep['web-scraper-start-url'].str.contains("juriquilla"),'nprecio'])
departamentos1['nmetros']=df_dep.loc[df_dep['web-scraper-start-url'].str.contains("juriquilla"),'nmetros']
departamentos=departamentos.iloc[0:453]

precio_depts=pd.DataFrame(departamentos['nprecio'])
metros_depts=pd.DataFrame(departamentos['nmetros'])

model_departamentos.fit(metros_depts,precio_depts)
model_departamentos.predict(pd.DataFrame([125]))



array([[19213.02551117]])

In [168]:
#DATA FRAME DE VALIDACION (30% restante) = departamentos_ok
departamentos_ok=pd.DataFrame(departamentos1.iloc[453:])

precio_depts_ok=pd.DataFrame(departamentos_ok['nprecio'])
metros_depts_ok=pd.DataFrame(departamentos_ok['nmetros'])

model_departamentos.fit(metros_depts_ok,precio_depts_ok)
model_departamentos.predict(pd.DataFrame([125]))

array([[18821.91167358]])

In [169]:
#MODELO PARA CASAS

df_casa['nprecio']=limpiar(df_casa['precio'])
df_casa['nprecio']=df_casa['nprecio']
df_casa['nprecio']=df_casa['nprecio'].replace(np.NaN,0)
df_casa['nmetros']=limpiar_m(df_casa['mets'])
df_casa['nmetros']=df_casa['nmetros'].replace(0,np.NaN)

model_casas=linear_model.LinearRegression()

#DATA FRAME DE ENTRENAMIENTO (70% de los datos) = casas
casas1=pd.DataFrame(df_casa.loc[df_casa['web-scraper-start-url'].str.contains("juriquilla"),'nprecio'])
casas1['nmetros']=df_casa.loc[df_casa['web-scraper-start-url'].str.contains("juriquilla"),'nmetros']

casas=casas1.iloc[0:1141]

precio_casas=pd.DataFrame(casas['nprecio'])
metros_casas=pd.DataFrame(casas['nmetros'])

model_casas.fit(metros_casas,precio_casas)
model_casas.predict(pd.DataFrame([492]))



array([[5774525.87088012]])

In [170]:
#DATA FRAME DE VALIDACION (30% restante) = departamentos_ok
casas_ok=pd.DataFrame(casas1.iloc[1141:])

precio_casas_ok=pd.DataFrame(casas_ok['nprecio'])
metros_casas_ok=pd.DataFrame(casas_ok['nmetros'])

model_casas.fit(metros_casas_ok,precio_casas_ok)
model_casas.predict(pd.DataFrame([492]))

array([[6887872.2805541]])